kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: prometheus-operated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
